---
title: "Model fitting Cell n201014-5"
author: "Alana"
date: "2022/5/26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = TRUE,warning = FALSE, message = FALSE)
```

# Parameter fitting
The firing rates of n201014-5 neuron is 7.27 spike/s.According to the simulation, the approximated input rate Ire for it is 460.
```{r}
ID=2
Ire=460
```
## Fit kHAP & lambda_HAP
```{r}
Vrest = -56 # Resting membrane potential
Vthresh = -50 # Threshold of action potential

# Synaptic input
eh = 2 # The EPSP magnitude
ih = -2 # The ISPS magnitude
lambda_syn = 3.5 # The PSP decay rate
Iratio = 1 # The ratio of IPSPs to EPSPs
epsprate = Ire / 1000 
ipsprate = epsprate * Iratio


# Post-spike potential
kHAPs = seq(20,80,5) # Magnitude parameter of hyperpolarising afterpotential (HAP)
lambda_HAPs = seq(6,12,0.5) # Half-life parameter of HAP
kAHP = 0.2 # Magnitude parameter of after hyperpolarising potential (AHP)
lambda_AHP = 350 # Half-life parameter of AHP

# Half-life parameter are converted to time strain
tausyn = log(2) / lambda_syn 
#tauHAP = log(2) / lambda_HAP
tauAHP = log(2) / lambda_AHP

#run time
runtime = 1000 # simulation time in second
numsteps = runtime * 1000 # simulation time in ms
```

```{r}
HAP_fit=data.frame()
for(kHAP in kHAPs){
  for(lambda_HAP in lambda_HAPs){
    
  # Initialize values
  Vsyn = 0 # Synaptic input signal
  HAP = 0 
  AHP = 0
  time = 0
  hstep = 1 #(the time step in ms) 
  spikecount = 0
  tepsp = 0
  tipsp = 0
  tauHAP = log(2) / lambda_HAP
  spiketime=c()
  
  for(i in 1:numsteps) { 
    # generate EPSPs
    nepsp = 0
    while (tepsp < hstep) {
      rand = runif(1)
      nepsp = nepsp + 1
      tepsp = - log(1 - rand)/epsprate+tepsp
    }
    tepsp = tepsp - hstep 
    #// generate IPSPs 
    nipsp = 0
    while (tipsp < hstep) {
      rand = runif(1)
      nipsp = nipsp + 1
      tipsp = - log(1 - rand) / ipsprate + tipsp
    }
    tipsp = tipsp - hstep
    inputsyn = nepsp * eh + nipsp * ih
 
    # membrane variables
    Vsyn = Vsyn + inputsyn - Vsyn * tausyn 
    HAP = HAP - HAP * tauHAP
    AHP = AHP - AHP * tauAHP
    V = Vrest + Vsyn - HAP - AHP
    
    if(V > Vthresh) {
    spikecount = spikecount + 1
    spiketime[spikecount] = i
  
    # add the post-spike potentials
    HAP = HAP + kHAP
    AHP = AHP + kAHP
    }}
  spiketime=spiketime/1000 # Convert to (s) scale
  ds=cbind(rep(paste0('kHAP_',kHAP),length(spiketime)),rep(paste0('lambda_HAP_',lambda_HAP),length(spiketime)),spiketime)
  HAP_fit=rbind(HAP_fit,ds)
}}
colnames(HAP_fit)[1]='kHAP'
colnames(HAP_fit)[2]='lambda_HAP'
```
### Calculate ISI
```{r}
HAP_fit_ISI=data.frame()
for(kHAP in kHAPs){
  for(lambda_HAP in lambda_HAPs){
  spiketimedt=HAP_fit[which(HAP_fit$kHAP==paste0('kHAP_',kHAP)&HAP_fit$lambda_HAP==paste0('lambda_HAP_',lambda_HAP)),]
  spiketimedt$spiketime=as.numeric(as.character(spiketimedt$spiketime))
  ISI=c()
  for (i in 1:(length(spiketimedt$spiketime)-1)){
    ISI=c(ISI,spiketimedt$spiketime[i+1]-spiketimedt$spiketime[i])
  }
  ds=cbind(rep(paste0('kHAP_',kHAP),length(ISI)),rep(paste0('lambda_HAP_',lambda_HAP),length(ISI)),ISI)
  HAP_fit_ISI=rbind(HAP_fit_ISI,ds)
  }
}
HAP_fit_ISI=data.frame(HAP_fit_ISI)
HAP_fit_ISI$HAP=paste(HAP_fit_ISI$V1,HAP_fit_ISI$V2,sep = '-')
colnames(HAP_fit_ISI)[4]='Cell_ID'
HAP_fit_ISI$ISI=as.numeric(as.character(HAP_fit_ISI$ISI))
```

# Compare with cell data
## Read in data
```{r}
home="/Users/chenghui/Documents/synoptic/cell data/"
Cell_ISI=read.csv(paste0(home,"Cell_ISI.csv"))
Cell_Hazard=read.csv(paste0(home,"Cell_Hazard.csv"))
Cell_ID=unique(Cell_ISI$Cell_ID)
# ID=2
```

## Calculate root mean square error
```{r}
RMSE=data.frame(check.names=F)
celldt=Cell_ISI[which(Cell_ISI$Cell_ID==Cell_ID[ID]),2:3]
cellhist=hist(celldt$ISI,breaks=seq(0,max(celldt$ISI)+0.005,0.005),plot = F)
for(kHAP in kHAPs){
  for(lambda_HAP in lambda_HAPs){
    modeldt=HAP_fit_ISI[which(HAP_fit_ISI$Cell_ID==paste0('kHAP_',kHAP,'-lambda_HAP_',lambda_HAP)),3:4]
    modelhist=hist(modeldt$ISI,breaks=seq(0,max(modeldt$ISI)+0.005,0.005),plot = F)
    mse=0
    binnum=min(length(cellhist$density),length(modelhist$density))
    for(i in 1:binnum){
      mse=mse+(cellhist$density[[i]]-modelhist$density[[i]])^2
    }
    rmse=c(kHAP,lambda_HAP,sqrt(mse/binnum))
    RMSE=rbind(RMSE,rmse)
  }
}
colnames(RMSE)=c('kHAP','lambda_HAP','rmse')
print(RMSE[order(RMSE$rmse)[1:10],])
```
For Cell 2, or desity plot fitting, k and lambda together, k=50, lambda=8

HAP
```{r}
library(ggplot2)
ISI_combine=rbind(Cell_ISI[which(Cell_ISI$Cell_ID==Cell_ID[ID]),2:3],HAP_fit_ISI[,3:4])
ISI_combine=rbind(Cell_ISI[which(Cell_ISI$Cell_ID==Cell_ID[ID]),2:3],HAP_fit_ISI[which(HAP_fit_ISI$Cell_ID=='kHAP_50-lambda_HAP_8'),3:4])
#ggplot(ISI_combine,aes(x=ISI,color=Cell_ID))+geom_histogram(binwidth = 0.005)+xlim(-0.1,1)+theme_classic()+xlab('ISI (s)')+ylab('Count')
ggplot(ISI_combine,aes(x=ISI,color=Cell_ID))+geom_density()+xlim(-0.1,1)+theme_classic()+xlab('ISI (s)')+ylab('Count')+
  theme(axis.title.x =element_text(size=13), axis.title.y=element_text(size=13),
        axis.title=element_text(size=13),axis.text = element_text(size=11) ,legend.text = element_text(size=10),
        legend.title = element_text(size=10))
``` 