---
title: "Leaky Integrate-and-fire Model for Oxytocin Neuron Modelling"
author: "814"
date: "2022/5/20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = TRUE,warning = FALSE, message = FALSE)
```

# Oxytocin neuron modelling
We built a leaky integrate-and-fire model to simulate the spiking behaviour of oxytocin neurons. The model below ran with default parameters.
## Initialize parameters
```{r}
Vrest = -56 # Resting membrane potential
Vthresh = -50 # Threshold of action potential

# Synaptic input
eh = 2 # The EPSP magnitude
ih = -2 # The ISPS magnitude
lambda_syn = 3.5 # The PSP decay rate
Ire = 300 # The input rate /s
Iratio = 1 # The ratio of IPSPs to EPSPs

# Post-spike potential
kHAP = 30 # Magnitude parameter of hyperpolarising afterpotential (HAP)
lambda_HAP = 7.5 # Half-life parameter of HAP
kAHP = 0.2 # Magnitude parameter of after hyperpolarising potential (AHP)
lambda_AHP = 350 # Half-life parameter of AHP
```

```{r}
# Half-life parameter are converted to time strain
tausyn = log(2) / lambda_syn 
tauHAP = log(2) / lambda_HAP
tauAHP = log(2) / lambda_AHP
```


```{r}
Vsyn = 0 # Synaptic input signal
HAP = 0 
AHP = 0
time = 0
hstep = 1 #(the time step in ms) 
runtime = 1000 # simulation time in second
numsteps = runtime * 1000 # simulation time in ms
spikecount = 0
tepsp = 0
tipsp = 0
epsprate = Ire / 1000 
ipsprate = epsprate * Iratio
spiketime=c()
```

## Model
```{r}
for(i in 1:numsteps) { 
  # generate EPSPs
  nepsp = 0
  while (tepsp < hstep) {
    rand = runif(1)
    nepsp = nepsp + 1
    tepsp = - log(1 - rand)/epsprate+tepsp
  }
  tepsp = tepsp - hstep 
  #// generate IPSPs 
  nipsp = 0
  while (tipsp < hstep) {
    rand = runif(1)
    nipsp = nipsp + 1
    tipsp = - log(1 - rand) / ipsprate + tipsp
  }
  tipsp = tipsp - hstep
  inputsyn = nepsp * eh + nipsp * ih
  
  # membrane variables
  Vsyn = Vsyn + inputsyn - Vsyn * tausyn 
  HAP = HAP - HAP * tauHAP
  AHP = AHP - AHP * tauAHP
  V = Vrest + Vsyn - HAP - AHP
  
  if(V > Vthresh) {
  spikecount = spikecount + 1
  spiketime[spikecount] = i

  # add the post-spike potentials
  HAP = HAP + kHAP
  AHP = AHP + kAHP
  }}

spiketime=spiketime/1000 # Convert to (s) scale
```

#Plot ISI
```{r}
ISI=c()
for (i in 1:(length(spiketime)-1)){
  ISI=c(ISI,spiketime[i+1]-spiketime[i])
}
ISI=data.frame(ISI)
library(ggplot2)
library(ggpubr)
plotISI=ggplot(ISI,aes(x=ISI))+geom_histogram(binwidth = 0.005,fill='grey')+
         theme_classic()+xlab('ISI (s)')+xlim(0,max(ISI$ISI))
plotISI
ggsave("~/Documents/synoptic/cell data/ModelISI.png",plotISI)
```

# Normalized ISI
```{r}
ISIhist=hist(ISI$ISI,plot = F,seq(0,max(ISI$ISI)+0.005,0.005))
ISIhist$counts=ISIhist$counts/sum(ISIhist$counts)
  #plot(ISIhist)
  #axis(side=1,c(0,3,0.5))
  #axis(side=2,c(0,800,200))
ISInorm=data.frame(ISIhist$breaks[1:length(ISIhist$breaks)-1]+
                    (ISIhist$breaks[2]-ISIhist$breaks[1])/2,ISIhist$counts)
colnames(ISInorm)=c('ISI','norm_count')
ISInormplot=ggplot(ISInorm,aes(x=ISI,y=norm_count))+
         geom_bar(stat='identity',width = 0.005,fill='grey')+
         theme_classic()+scale_y_continuous(expand = c(0,0),limits = c(0,0.05))+
         xlab('ISI (s)')+ylab('Count (%)')
ISInormplot
ggsave("~/Documents/synoptic/cell data/ModelnormISI.png", ISInormplot)
```

# Plot Hazard
```{r}
celldt=data.frame(spiketime)
spikecount=length(celldt[,1])
plothist=hist(ISI$ISI,breaks=seq(0,max(ISI$ISI)+0.005,0.005),plot = F)
hist=plothist$counts
haz=c()
bincount=length(plothist$counts)
hazcount=0
for(j in 1:bincount){
    haz[j]=hist[j]/(spikecount-hazcount)
    hazcount=hazcount+hist[j]
}
  #plot(c(1:bincount)*0.005,haz)
time=c(1:bincount)*0.005
hazarddt=data.frame(time,haz)
plothazard=ggplot(hazarddt,aes(x=time,y=haz))+
    geom_point(color='#1F77B4FF',size=2,alpha=0.6)+
    theme_classic()+labs(title = 'Model')+xlab('Time (s)')+ylab('Hazard')+
    xlim(0,0.5)+ylim(0,0.1)
plothazard
```
